apiVersion: v1
description: 'Kubeform by AppsCode - Build Cloud Infrastructure from Kubernetes'
name: kubeform
version: v0.1.0
appVersion: v0.1.0
home: https://github.com/kubeform/kubeform
#icon: https://avatars2.githubusercontent.com/u/52143707?s=200&v=4
sources:
  - https://github.com/kubeform/kubeform
maintainers:
  - name: appscode
    email: support@appscode.com