apiVersion: v1
description: 'Kubeform by AppsCode - Provision cloud resources using Kubernetes CRDs
  & Terraform'
name: kubeform
version: v0.2.0
appVersion: v0.2.0
home: https://github.com/kubeform/kubeform
icon: https://cdn.appscode.com/images/products/kubeform/icons/android-icon-192x192.png
sources:
- https://github.com/kubeform/kubeform
maintainers:
- name: appscode
  email: support@appscode.com
